ingress:
  - hostname: api.otelmap.com
    service: http://nginx:80
  - hostname: otlp.otelmap.com
    path: /opentelemetry.proto
    service: h2c://otelcollector:4317
    originRequest:
      http2Origin: true
  - hostname: otlp.otelmap.com
    service: http://nginx:80
  - service: http_status:404
