version: "3"

services:
  otelcollector:
    image: otel/opentelemetry-collector-contrib:0.114.0
    container_name: otel
    command:
      - "--config=/etc/otel-collector-config.yml"
      - "--set=service.telemetry.logs.level=INFO"
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # otlp receiver
      - "4318:4318" # otlp http receiver
      - "13133:13133" # health_check extension
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - otel-clickhouse
      - web
  clickhouse:
    image: clickhouse/clickhouse-server:25.9
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    healthcheck:
      test:
        ["CMD", "bash", "-lc", "clickhouse-client --query 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    env_file:
      - path: ".env.production"
        required: true
    networks: 
      - otel-clickhouse
      - web
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./sql:/docker-entrypoint-initdb.d
      - ./clickhouse.xml:/etc/clickhouse-server/config.d/clickhouse.xml
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - otel-clickhouse
      - web
    depends_on:
      clickhouse:
        condition: service_healthy
    env_file:
      - path: ".env.production"
        required: true
    labels: []

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - otelcollector
      - clickhouse
    networks:
      - web

volumes:
  clickhouse_data:

networks:
  otel-clickhouse:
    driver: bridge
    internal: true
  web:
    driver: bridge
