receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500

  attributes/sensitive_data:
    actions:
      - key: user.*
        action: hash
      - key: auth.*
        action: delete
      - key: client.ip
        action: hash

  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  # resource:
  #   attributes:
  #     - key: service.name
  #       value: "serviceName"
  #       action: upsert

  # filter:
  #   traces:
  #     span:
  #       - 'resource.attributes["otelmap.session_token"] != nil'

  batch:
    send_batch_size: 100000
    timeout: 5s

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: default
    username: default
    password: default
    ttl: 6h
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, attributes/sensitive_data, batch]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, attributes/sensitive_data, batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, attributes/sensitive_data, batch]
      exporters: [clickhouse]
