name: Build and push server image

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - "Dockerfile"
      - "cmd/**"
      - "internal/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/docker-publish.yml"
  workflow_dispatch: {}

env:
  REGISTRY: otelmap-server.registry.dockreg.com
  IMAGE_NAME: otelmap-server

jobs:
  docker:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_API_TOKEN }}

      - name: Prepare tags
        id: meta
        shell: bash
        run: |
          sha_short="${GITHUB_SHA::7}"
          echo "sha_short=$sha_short" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .  
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
